### ISSUE TITLE
Open-source license

### ISSUE THREAD

**Issue by hobbes7878** [DallasMorningNews/chartwerk-editor#21]
Which?

**Comment by allanjamesvestal** [comment]
I favor the [GNU Affero GPL v3](https://choosealicense.com/licenses/agpl-3.0/), because — in addition to the protections of a BSD 3-clause license — the Affero license explicitly insulates from some patent claims, requires published changes to be released back to the project and specifically targets software that is run on a server.

One slight variant of the AGPL is the [European Union Public License v1.1](https://choosealicense.com/licenses/eupl-1.1/), which does all of the above, but also includes specific notes that users don't have rights to use the project's trademarks (a feature that sets the 3-clause BSD apart from older BSD variants). That's academic in a sense, though: GitHub's license-choosing site notes that "licenses without such a statement probably do not grant any implicit trademark rights".

**Comment by hobbes7878** [comment]
I'm just cribbing here but does this forward the right to charge for the software to downstream users?

**Comment by allanjamesvestal** [comment]
AGPL does appear to let downstream users charge others for the code. That said, a few important points:

-   BSD doesn't prohibit us (or others) from selling the code in the future.
-   Under BSD, someone could fork the repo and add new features, but not have to share those changes with us.
-   Under the AGPL, if someone did try to sell the code, we'd be entitled to a copy of the code they were selling — even if they made changes to it.
-   Someone could take code we licensed under BSD and re-release it as GPL, which would also preclude us from incorporating their changes into our work (because we couldn't move code from a more restrictively-licensed repo to our less restrictively-licensed one).

Take a look at [this Hacker News thread](https://news.ycombinator.com/item?id=1273231) and [this blog post](https://dragly.org/2014/11/22/choosing-the-right-license-for-your-code/) (and maybe the heading titled "Eat Me" on [this page](http://zguide.zeromq.org/page:all#header-136), if you don't mind extracting the valid point from the ... _baroque_ writing style). The message I'm seeing repeatedly is that for actual software products (rather than frameworks that enable coders to create software), GPL variants help to keep open software open in perpetuity.
