### ISSUE TITLE
Data Table headers sorting with numbers first

### ISSUE THREAD

**Issue by arianagiorgi** [DallasMorningNews/chartwerk-editor#49]
The datatable sorts the columns by ordering the columns with numbers as headers first.

![Datatable sorting](https://user-images.githubusercontent.com/6832094/34229701-db8889da-e59a-11e7-8059-90490e5cc8cc.png)

**Comment by hobbes7878** [comment]
I duplicated this behavior on ours. This should respect the given order.

Looks like sort order in API is incorrect at `chartwerk.datamap.sort`, which is set [here](https://github.com/DallasMorningNews/chartwerk-editor/blob/40b2532cabb68190342693ea584ae85528d58813/src/js/components/data/DataInput.jsx#L72-L79).

Looking at the [csvtojson](https://github.com/Keyang/node-csvtojson) library that gives the order, [one person had the same issue](https://github.com/Keyang/node-csvtojson/issues/187), which was fixed by turning off the type sniffing in [checkType param](https://github.com/Keyang/node-csvtojson#parameters). That is now false by default in current versions, so it may just need a version bump in this repo.

If that doesn't fix it, then I may need to set the header order from the raw data string _before_ converting to JSON, which I'll need to test against some other conditions...

Adding as bug for quick fix. (hi, ariana!)

**Comment by hobbes7878** [comment]
So on closer look, EMCA guarantees that keys that are integer-like will always come before alpha keys in JS objects (though alpha keys can be arbitrarily sorted).

So to sort data properties, chart templates should use the sort order in `chartwerk.datamap.sort`, which will be an array of the headers as sorted in the original data.

@arianagiorgi you may just need to adjust the data table chart template a little to get what you need now.
